### ISSUE TITLE
Feature request: override season/episode placement with .nfo file

### ISSUE THREAD

**Issue by timur-tabi** [xbmc/metadata.themoviedb.org.python#114] opened 2021-11-05 18:32 UTC
TMDB currently identifies all of the Doctor Who special episodes as belonging to "Season 0" and there are over 200 of them.  Although these specials are technically considered to be unaffiliated with a particular season of Doctor Who, many of them were aired in a particular order and it is expected to watch them before or after a particular season.

For example, the Doctor Who special episode "Resolution" is considered S00E156, but I think it should be considered S11E11.  Sure, officially S11 only had 10 episodes, but you're *supposed* to watch Resolution after you finish S11, so marking it as S11E11 would place the episode with the rest of S11 and make it easier to find.

Therefore, I would like a way to override the season/episode placement with an .nfo file.  I was hoping that this S00E156.nfo file would do the trick, but it appears that metadata.themoviedb.org.python ignores .nfo files:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<episodedetails>
    <title>Resolution</title>
    <showtitle>Doctor Who (2005)</showtitle>
    <uniqueid type="tmdb">57243</uniqueid>
    <season>0</season>
    <episode>156</episode>
    <displayseason>11</displayseason>
    <displayepisode>11</displayepisode>
    <original_filename>S00E156.mkv</original_filename>
</episodedetails>
```

**Comment by KarellenX** [comment] 2021-11-05 19:39
@timur-tabi 

This section of github is for reporting bugs, not feature requests. I'll close this. 
Feature requests can be posted on the forum here... https://forum.kodi.tv/forumdisplay.php?fid=9

But I do completely agree with you wanting to rearrange episodes, and I do exactly that for many tv shows (including Dr Who, regardless of how bad the last couple of seasons were ;) )

I tested your nfo file, and it works correctly here. Keep in mind the Season needs to already exist for the special episode to display. So if you add the special to S11, but you have no other episodes in S11, then the special file won't display. This method cannot create a new season.

Instead, why not reorganise your episode files?
Check this page on how to rearrange episodes... https://kodi.wiki/view/Convert_movie_to_episode

**Closed by KarellenX** 2021-11-05 19:39 UTC

**Comment by timur-tabi** [comment] 2021-11-06 01:41
In that case, I need to file a bug report because I do have all other 10 episodes of Season 11.  Is there some other kind of setting I need to enable to get it to see my .nfo file?

**Comment by KarellenX** [comment] 2021-11-06 03:06
But its not a bug as it works for me and have seen others on the forum using it. So no need to open a bug report.

The problem is local. First, the nfo file is a bit bare of information. Is this an nfo file you created manually?

Provide a debuglog which captures  you scraping the show and the nfo file. I might be able to spot the problem in the log.

Head over to the forum to continue support, and link to this issue in your first post on the forum.
