### ISSUE TITLE
Artwork from TMDb not scraping, probably due to link in description.

### ISSUE THREAD

**Issue by OsoaGH** [xbmc/metadata.themoviedb.org.python#80] opened 2021-07-03 10:19 UTC
[This](https://www.themoviedb.org/talk/60de0392a128560074955f5d) has been fixed on [this](https://kodi.wiki/view/Add-on:The_Movie_Database) scraper but not this one. Only artwork from fanart.tv is shown.

**Comment by rmrector** [comment] 2021-07-24 17:36
This Python scraper was not affected by that, you are likely seeing a combination of two behaviors this scraper has always had - there is a strict limit of 10 images for each art type, and fanart.tv artwork is listed first.

If that doesn't match your observations, I'll need some specific example movies to investigate further.

**Comment by OsoaGitHub** [comment] 2021-07-24 17:56
Is it possible to change the limit?

**Comment by OsoaGitHub** [comment] 2021-07-29 20:25
Hey @rmrector sorry for the ping, but can I get an answer to my question please?

**Comment by rmrector** [comment] 2021-07-30 00:55
The limit is in place due to a bug in Kodi. The bug in Kodi can be fixed by someone willing to put in the effort.

https://github.com/xbmc/xbmc/issues/15768

**Comment by KarellenX** [comment] 2022-04-29 03:06
Can we close this @rmrector ?
It's not a bug, but intended behaviour.

**Closed** 2022-05-02 22:55 UTC
Labels: help wanted

**Comment by OsoaGH** [comment] 2022-06-19 20:01
Sorry for reviving a dead topic, but why does this bug only affect this addon and not the other TMDB scraper?

**Comment by KarellenX** [comment] 2022-06-19 21:02
Which bug? Can you explain what you are expecting, and what happens instead?
You are referring to something from a year ago and, if it was a problem, the forum would have been flooded with complaints.
Thanks.

**Comment by OsoaGH** [comment] 2022-06-20 17:07
> The limit is in place due to a bug in Kodi. The bug in Kodi can be fixed by someone willing to put in the effort.
> 
> [xbmc/xbmc#15768](https://github.com/xbmc/xbmc/issues/15768)

I'm refering to this bug, which apparently limits the amount of artwork the plugin can scrape to 10. I've only seen it affect this addon however

**Comment by KarellenX** [comment] 2022-06-20 19:37
oh, that is not a bug. That is intended behaviour.
How many artwork do you want? Why would you potentially want 50 or 100 fanart links?

This is not the only scraper that has the limitation. TMDB TV Shows, TV Maze and this scraper have it. 
The older XML scrapers do not have it, and they are the ones that cause problems for users using MySQL/MariaDB setups.

**Comment by KarellenX** [comment] 2022-06-20 19:42
I haven't tried, but I guess you could modify this line on your own setup and test if it works...
https://github.com/xbmc/metadata.themoviedb.org.python/blob/master/python/scraper.py#L82-L85
Of course, each time the scraper is updated, your edit will be reset.
